name: Build RSDK

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Build_ps3:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Downlod Dependencies (Toolchain)
      run: |
        sudo apt-get install -y autoconf automake bison flex gcc libelf-dev make
        sudo apt-get install -y texinfo libncurses5-dev patch python2 python-is-python3 subversion wget zlib1g-dev
        sudo apt-get install -y libtool libtool-bin python2-dev python-dev-is-python3 bzip2 libgmp3-dev pkg-config g++
        sudo apt-get install -y libssl-dev clang nvidia-cg-toolkit
        
      # Download and make toolchain
    - name: Download PSL1GHT Toolchain
      run: |
        git clone -b gcc-7.5.0 https://github.com/StrawFox64/PS3Toolchain.git
        sudo chmod -R 777 PS3Toolchain
        cd PS3Toolchain
        ./toolchain-sudo.sh
    - name: Download dependencies (Project)
      run: |
        git clone https://github.com/nothings/stb.git
        git clone https://github.com/leethomason/tinyxml2.git
        git clone https://github.com/StrawFox64/Sonic-Mania-Decompilation.git
        
    - name: Move dependencies (Project)
      run: |
        cd Sonic-Mania-Decompilation
        mv SonicMania ../RSDKv5 && cd ..
        mv tinyxml2/* dependencies/all/tinyxml2
        mv stb/* dependencies/all/stb_vorbis
        
    - name: Build self
      run: |
        cd RSDKv5.ps3
        export PKG_CONFIG_PATH=$PS3DEV/portlibs/ppu/lib/pkgconfig/
        make
    - name: Push package artifact
      uses: actions/upload-artifact@v3
      with:
        name: RSDKv5_${{ env.sha_name }}
        path: RSDKv5.self
        if-no-files-found: error
        # don't keep artifacts for too long
        retention-days: 7
