name: Build RSDK

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Build_ps3:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Configure environment
      run: |
        echo "PS3DEV=/usr/local/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=/usr/local/ps3dev" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/local/ps3dev/portlibs/ppu/lib/pkgconfig" >> $GITHUB_ENV
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "export NUM_COMMITS=$(git rev-list --count --author=StrawFox64 origin/master)" >> $GITHUB_ENV
        
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/StrawFox64/StrawFox64.github.io/releases/download/psl1ght-gcc7.5.0-ubuntu-22.04/ps3dev.tar.gz | sudo tar xvz -C /usr/local
  
    - name: Download dependencies (RSDK)
      run: |
        git clone https://github.com/nothings/stb.git
        git clone https://github.com/leethomason/tinyxml2.git
        git clone https://github.com/StrawFox64/Sonic-Mania-Decompilation.git
        
    - name: Move dependencies (RSDK)
      run: |
        cd Sonic-Mania-Decompilation
        mv SonicMania ../RSDKv5 && cd ..
        mv tinyxml2/* dependencies/all/tinyxml2
        mv stb/* dependencies/all/stb_vorbis
        
    - name: Build self
      run: |
        cd .github/workflows && make && mv RSDKv5.self EBOOT.BIN
        
    - name: Push package artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: RSDKv5_${{ env.sha_name }}_$NUM_COMMITS
        path: .github/workflows/EBOOT.BIN
        if-no-files-found: error
        # don't keep artifacts for too long
        retention-days: 7
