name: Build RSDK

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Build_ps3:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set env vars
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/StrawFox64/StrawFox64.github.io/releases/download/ps3dev-GCC7.5.0-ubuntu/ps3dev-GCC-7.5.0.tar.gz | tar xvz -C ./

    - name: Download dependencies
      run: |
        git clone https://github.com/nothings/stb.git
        git clone https://github.com/leethomason/tinyxml2.git
        git clone https://github.com/StrawFox64/Sonic-Mania-Decompilation.git
        
    - name: Move dependencies (Project)
      run: |
        cd Sonic-Mania-Decompilation
        mv SonicMania ../RSDKv5
        cd ..
        mv tinyxml2/* dependencies/all/tinyxml2
        mv stb/* dependencies/all/stb_vorbis
        
    - name: Build self
      run: |
        cd RSDKv5.ps3
        export PKG_CONFIG_PATH=$PS3DEV/portlibs/ppu/lib/pkgconfig/
        make

    - name: Push package artifact
      uses: actions/upload-artifact@v3
      with:
        name: RSDKv5_${{ env.sha_name }}
        path: RSDKv5.self
        if-no-files-found: error
        # don't keep artifacts for too long
        retention-days: 7
