name: Build RSDK

on: [ push, pull_request, workflow_dispatch ]

jobs:
  Build_ps3:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Downlod Dependencies (Toolchain)
      run: |
        sudo apt-get install -y autoconf automake bison flex gcc libelf-dev make \
        texinfo libncurses5-dev patch python2 python-is-python3 subversion wget zlib1g-dev \
        libtool libtool-bin python2-dev python-dev-is-python3 bzip2 libgmp3-dev pkg-config g++ \
        libssl-dev clang nvidia-cg-toolkit

    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/StrawFox64/StrawFox64.github.io/releases/download/ps3dev-GCC7.5.0-ubuntu/ps3dev.tar.gz | sudo tar xvz -C /usr/local
  
    - name: Download dependencies (RSDK)
      run: |
        git clone https://github.com/nothings/stb.git
        git clone https://github.com/leethomason/tinyxml2.git
        git clone https://github.com/StrawFox64/Sonic-Mania-Decompilation.git
        
    - name: Move dependencies (RSDK)
      run: |
        cd Sonic-Mania-Decompilation
        mv SonicMania ../RSDKv5 && cd ..
        mv tinyxml2/* dependencies/all/tinyxml2
        mv stb/* dependencies/all/stb_vorbis
        
    - name: Build self
      run: |
        cd RSDKv5.ps3
        ./path.sh
        
    - name: Push package artifact
      uses: actions/upload-artifact@v3
      with:
        name: RSDKv5_${{ env.sha_name }}
        path: RSDKv5.ps3/RSDKv5.self
        if-no-files-found: error
        # don't keep artifacts for too long
        retention-days: 7
